### ISSUE TITLE
If I have cursor anywhere inside the comment, it should uncomment the whole thing.

### ISSUE THREAD

**Issue by trusktr** [philsinatra/html-nested-comments#10]
For example, suppose I start with the following and the `|` represents the location of my cursor:

```html
<div>
    <!--
    <p>some| content</p>
    <p>other content</p>
    -->
</div>
```

then if I run the command I would expect it to uncomment that like this:

```html
<div>
    <!--
    <p>some| content</p>
    <p>other content</p>
    -->
</div>
```

but instead it makes a new comment inside the comment which causes a syntax error:

```html
<div>
    <!--
    <p>some<!--  -->| content</p>
    <p>other content</p>
    -->
</div>
```

**Comment by philsinatra** [comment]
Basing the functionality on user selection allows for a more predictable experience. There may be multiple comments within a section and the desired effect is to only effect specific areas within that area with this functionality, which is safely achieved by using the selection as the effected range.
