### ISSUE TITLE
Move cursor into empty comment

### ISSUE THREAD

**Issue by trusktr** [philsinatra/html-nested-comments#11]
It'd be great if the cursor would move into the empty comment automatically.

F.e., if I have my cursor on an empty line:

```html
|
```

then toggle the comment, I get

```html
<!-- -->|
```

but it'd be neat if it put my cursor in it:

```html
<!-- | -->
```

**Comment by philsinatra** [comment]
The current functionality is based on the default commenting functionality within the app, which is to place the cursor after the comment in the cases of a blank line. I prefer to keep the functionality in line with the app defaults for consistency in user experience.
