### ISSUE TITLE
Not converted nested comments

### ISSUE THREAD

**Issue by ghost** [philsinatra/html-nested-comments#3]
This looks like exactly what I need but I can't seem to get it to work on my system.  I am using Atom 1.5.3 on Windows 7 system.  Existing comment tags are not replaced with  <!~~ or ~~>.  Any idea why this may be the case??

**Comment by philsinatra** [comment]
I haven't seen any other issues. Is there a conflict with your key binding? Does it work if you use the Fuzzy Finder or app menu to trigger the plugin?

**Comment by ghost** [comment]
The app menu does nothing for me.  It works if I trigger the fuzzy finder
and then press ctrl-/.  I just changed the key binding to alt-/ and that
seems to fix it.

thanks for response!

David

**Comment by philsinatra** [comment]
More than likely the default key binding is conflicting with something else you have installed. Glad it's working now.
