### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mxshdev** [philsinatra/html-nested-comments#4]
Not working. Conflict with default atom keybindings. Why?

**Comment by philsinatra** [comment]
Is it totally not working or do you have a keybinding conflict only? Does it work via the command palette?

**Comment by mxshdev** [comment]
Yes, it not working with keybind Ctrl + /

**Comment by philsinatra** [comment]
There's probably a conflict with that keybinding and some other plugin you have installed. You'll need to find the duplicate bindings and change one of them to whatever you want to use instead.
