### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mxshdev** [philsinatra/html-nested-comments#5]
The clean install does not work. Because there is an overload of the standard keybinding atom. I was reassigned to shift+ctrl+/ and it didn't help. He just puts empty comments, and sometimes does not work.

**Comment by philsinatra** [comment]
1. Are you selecting text properly for the expected functionality? Refer to the image in the README for an example of how to highlight before applying the package.
2. If you have a keyboard binding conflict, there are other ways to trigger the package to test if it's working properly. Try activating it via the Command Palette: 
- <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>P</kbd>
- Type 'nest' to filter the options

![screen shot 2016-06-02 at 8 30 27 am](https://cloud.githubusercontent.com/assets/1465808/15744832/5fd359e4-289c-11e6-8259-4cb86f9e5776.png)

**Comment by gitdistill** [comment]
this is not working for me either

![screenshot 2016-06-02 10 37 15](https://cloud.githubusercontent.com/assets/2692764/15754659/134594fe-28ae-11e6-8dd0-8ba2318994ff.png)
![screenshot 2016-06-02 10 38 13](https://cloud.githubusercontent.com/assets/2692764/15754668/2060e8fa-28ae-11e6-8da4-beed4afa0138.png)

**Comment by gitdistill** [comment]
correction

running manually from command palette works!

Seems like a key binding issue, although I have no custom key bindings, or packages related to key binding.

**Comment by philsinatra** [comment]
Use the Keybinding Resolver (<kbd>command</kbd> + <kbd>.</kbd>) to confirm there isn't a duplicate key binding causing the issue.
