### ISSUE TITLE
Comments in PHP file is messy

### ISSUE THREAD

**Issue by jpenna** [philsinatra/html-nested-comments#7]
Thanks for this package, helped a lot with HTML!

I am using it now in PHP files, but it is not detecting the right scope to add the `<!-- -->` (HTML syntax) or `//` (PHP syntax).

It inserts the `<!-- -->` inside of PHP context (which is between `<?php ... ?>`), and then breaks the code.

**Comment by philsinatra** [comment]
Can you give me an example of the code you're using the package on and show where it's giving you a problem?

**Comment by jpenna** [comment]
Something like this:

```
<div>
  <?php 

    // We are in PHP context
    /* Comments may have these notations */

    <!-- print_r('xxx'); --> // But the extension is using the HTML comments inside PHP markup  
  
  ?>

  <!-- Right HTML comment notation here -->

</div>
```

**Comment by philsinatra** [comment]
The package is for HTML code only; it is not intended to replace the built in commenting functionally. You should use the built in commenting functionality when working with your PHP code and trigger this package when you're dealing with HTML that includes other comments.
