### ISSUE TITLE
just add jsx/vue files

### ISSUE THREAD

**Issue by janat08** [philsinatra/html-nested-comments#8]
would you just add jsx/vue extensions to list?

**Comment by philsinatra** [comment]
Doesn't `jsx` use block commenting?

```jsx
/* Block style comments */
```

**Comment by janat08** [comment]
I don't actually use it. Going by 2015 article it checks out, and sounds like still would be legit.

**Comment by janat08** [comment]
Anyhow vue is rad, and deserves default support.

**Comment by philsinatra** [comment]
`.vue` extension has been added to the supported syntax list. `.jsx` does not use HTML formatted comments, so I did not add support for that syntax.

**Comment by janat08** [comment]
I don't think that vue works, and readme doesn't list it.
